id: P003033
initial_creation_type: ocr
source_metadata:
  id: bdr:W23718
  title: བྱ་བཏང་ཚོགས་དྲུག་རང་གྲོལ་གྱིས་རང་དང་སྐལ་ལྡན་གདུལ་བྱ་ལ་མགྲིན་པ་གདམས་པའི་བང་མཛོད་ནས་གླུ་དབྱངས་དགའ་སྟོན་འགྱེད་པ་རྣམས་བཞུགས
  author: ''
  volumes: {}
