id: P003033
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:35:38.408840
source_metadata:
  id: bdr:W23718
  title: བྱ་བཏང་ཚོགས་དྲུག་རང་གྲོལ་གྱིས་རང་དང་སྐལ་ལྡན་གདུལ་བྱ་ལ་མགྲིན་པ་གདམས་པའི་བང་མཛོད་ནས་གླུ་དབྱངས་དགའ་སྟོན་འགྱེད་པ་རྣམས་བཞུགས
  author: ''
  volumes:
    5b416e879b514eef9afc06acde819915:
      image_group_id: I1737
      title: ''
      volume_number: 1
      total_pages: 523
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
